-- Auto-generated SQL inserts for tax code from markdown file (Part 2: Structure - Livres, Parties, Titres)
-- Generated on: 2025-04-20

INSERT INTO code_sections (type, code, title, content, page_number_start, page_number_end, version_date) VALUES ('livre', 'LIVRE I', 'IMPOTS D’ETAT', '', 0, NULL, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'LIVRE I' LIMIT 1), 'titre', 'TITRE II', 'IMPOT SYNTHETIQUE', '', 32, 36, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'LIVRE I' LIMIT 1), 'titre', 'TITRE III', 'IMPOT SUR LES REVENUS SALARIAUX ET ASSIMILES (IRSA)', '', 37, 41, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'LIVRE I' LIMIT 1), 'titre', 'TITRE IV', 'IMPOTS SUR LES REVENUS DES CAPITAUX MOBILIERS', '', 42, 44, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'LIVRE I' LIMIT 1), 'titre', 'TITRE V', 'IMPOT SUR LES PLUS VALUES IMMOBILIERES (IPVI)', '', 45, NULL, '2025-04-20');
INSERT INTO code_sections (type, code, title, content, page_number_start, page_number_end, version_date) VALUES ('livre', 'LIVRE II', 'IMPOTS LOCAUX', '', 134, NULL, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'LIVRE II' LIMIT 1), 'titre', 'TITRE I', 'IMPOT FONCIER SUR LES TERRAINS (IFT)', '', 135, 134, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'LIVRE II' LIMIT 1), 'titre', 'TITRE VI', 'IMPOT DE LICENCE', '', 135, 134, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'LIVRE II' LIMIT 1), 'titre', 'TITRE VII', 'TAXE ANNUELLE SUR LES APPAREILS AUTOMATIQUES', '', 135, 134, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'LIVRE II' LIMIT 1), 'titre', 'TITRE VIII', 'TAXE SUR LES EAUX MINERALES', '', 135, 134, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'LIVRE II' LIMIT 1), 'titre', 'TITRE IX', 'TAXE SUR LA PUBLICITE', '', 135, 134, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'LIVRE II' LIMIT 1), 'titre', 'TITRE X', 'TAXE SUR L’EAU ET/OU L’ELECTRICITE', '', 135, 134, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'LIVRE II' LIMIT 1), 'titre', 'TITRE XI', 'TAXE SUR LES FETES, SPECTACLES ET MANIFESTATIONS DIVERSES', '', 135, 134, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'LIVRE II' LIMIT 1), 'titre', 'TITRE XII', 'TAXE SUR LES PYLONES, RELAIS, ANTENNES OU MATS', '', 135, 134, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'LIVRE II' LIMIT 1), 'titre', 'TITRE XIII', 'TAXE SUR LES JEUX RADIOTELEVISES', '', 135, NULL, '2025-04-20');
INSERT INTO code_sections (type, code, title, content, page_number_start, page_number_end, version_date) VALUES ('livre', 'LIVRE III', 'DISPOSITIONS COMMUNES', '', 135, 134, '2025-04-20');
INSERT INTO code_sections (type, code, title, content, page_number_start, page_number_end, version_date) VALUES ('livre', 'LIVRE IV', 'REGIMES SPECIFIQUES', '', 135, NULL, '2025-04-20');
