-- Auto-generated SQL inserts for tax code from markdown file (Part 3: Chapters and Sections)
-- Generated on: 2025-04-20

INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE I', 'PRINCIPE', '', 7, 6, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE II', 'CHAMP D’APPLICATION', '', 7, NULL, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE II' LIMIT 1), 'section', 'SECTION I', 'REVENUS IMPOSABLES', '', 7, 10, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE II' LIMIT 1), 'section', 'SECTION II', 'REVENUS EXONERES', '', 11, 11, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE II' LIMIT 1), 'section', 'SECTION III', 'TERRITORIALITE', '', 12, 11, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE II' LIMIT 1), 'section', 'SECTION IV', 'PERSONNES IMPOSABLES', '', 12, NULL, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE III', 'FAIT GENERATEUR', '', 13, 12, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE IV', 'BASE D’IMPOSITION', '', 13, 17, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE V', 'LIEU D’IMPOSITION', '', 18, 17, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE VI', 'REGIME D’IMPOSITION', '', 18, 19, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE VII', 'CALCUL DE L’IMPOT', '', 20, 22, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE VIII', 'PAIEMENT DE L’IMPOT', '', 23, 23, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE IX', 'REDUCTION D’IMPOT A RAISON DES PERSONNES A CHARGE', '', 24, 23, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE X', 'OBLIGATIONS DES CONTRIBUABLES', '', 24, 24, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE XI', 'DISPOSITIONS DIVERSES', '', 25, NULL, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE XI' LIMIT 1), 'section', 'SECTION V', 'CALCUL DE L’IMPOT', '', 45, 45, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE XI' LIMIT 1), 'section', 'SECTION VI', 'RECOUVREMENT', '', 46, 45, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE XI' LIMIT 1), 'section', 'SECTION VII', 'OBLIGATIONS DU CONTRIBUABLE', '', 46, 78, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE XI' LIMIT 1), 'section', 'SECTION VIII', 'FINANCES – COMPTABILITE PUBLIQUE', '', 79, 78, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE XI' LIMIT 1), 'section', 'SECTION IX', 'ASSISTANCE JUDICIAIRE', '', 79, 80, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE XI' LIMIT 1), 'section', 'SECTION X', 'DISPOSITIONS DIVERSES', '', 81, NULL, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE V' LIMIT 1), 'chapitre', 'CHAPITRE XII', 'TAXATION D’OFFICE', '', 121, 120, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE V' LIMIT 1), 'chapitre', 'CHAPITRE XIII', 'I- PENALITES SPECIFIQUES', '', 121, 120, '2025-04-20');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE V' LIMIT 1), 'chapitre', 'CHAPITRE XIV', 'DISPOSITIONS DIVERSES', '', 121, NULL, '2025-04-20');
