-- Auto-generated SQL inserts for tax code from markdown file (Part 4: Articles)
-- Generated on: 2025-04-20

-- Insert articles with parent references
-- We'll use a different approach here to avoid explicit IDs
-- Instead, we'll reference the parent chapter by its code

-- First, let's create a temporary variable to store the parent ID for the articles
DO $$
DECLARE
    parent_id_var INTEGER;
BEGIN
    -- Get the ID of the chapter/section that will contain these articles
    SELECT id INTO parent_id_var FROM code_sections 
    WHERE code = 'CHAPITRE I'
    LIMIT 1;

    -- Insert articles for CHAPITRE I
    INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) 
    VALUES 
    (parent_id_var, 'article', 'ART. 01.01.46', E'Article 01.01.46', E'Sont affranchis de l’impôt sur les marchés publics mais demeurent imposables à l’Impôt sur les revenus ou à l’Impôt synthétique :\n\n- les revenus des fournisseurs d’eau et d’électricité au profit d’une personne publique ;\n\n- les revenus issus des marchés publics énumérés à l’article 4 IV du Code des marchés publics, exceptés ceux obtenus de la location d’immeubles à une personne publique ;\n\n- Les revenus des marchés de faible montant qui sont dispensés de mise en concurrence formelle et exécutés directement par bon de commande.\n\nQuel que soit le montant, les revenus issus des ventes de biens et services ayant fait l’objet d’un contrat préalable tel qu’un contrat d’abonnement dont le montant facturé peut varier d’une période à l’autre ou non ainsi que les revenus obtenus de la location d’immeubles à une personne publique demeurent, néanmoins passibles de l’Impôt sur les Marchés Publics. Il en est de même pour les revenus issus des marchés à tranches comportant une tranche ferme et une ou plusieurs tranches conditionnelles ;\n\n- les revenus des fournisseurs de biens et de prestations commandées par les bailleurs et offerts à titre de dons mais directement accordés au profit des personnes privées ou des particuliers n’entrant pas dans le cadre d’une politique publique ainsi que les revenus des marchés lancés avant la Loi de Finances 2020 financés sur fonds d’origine extérieure ;\n\n- les revenus des fournisseurs des produits pétroliers issus des ventes au profit d’une personne publique.\n\n- les revenus des fournisseurs issus de la vente locale des Aliments thérapeutiques prêts à l’emploi, des Produits nutritionnels spécialisés, au profit d’une personne publique ;\n\n- les revenus des fournisseurs issus des ventes des timbres-poste par la Paositra Malagasy, des cartes téléphoniques, des journaux, au profit d’une personne publique ;\n\n- Les rémunérations que prennent les établissements de crédit/financiers et assimilés, en échange de services payés par une personne publique et/ou à son profit ;\n\n- les revenus des fournisseurs de biens et services issus des marchés financés sur des fonds “Responsabilité sociétale des entreprises (RSE) destinés à des activités d’intérêt général ;\n\n- les revenus des fournisseurs de biens et services issus des marchés ou des transactions conclus avec la Banky Foiben’i Madagasikara.', 30, NULL, '2025-04-20'),
    (parent_id_var, 'article', 'ART. 03.03.01', E'Article 03.03.01', E'Les droits, taxes et autres recettes en matière de droits indirects sont liquidés et recouvrés au niveau du Centre fiscal territorialement compétent.\n\nArticle 03.03.02.- Les droits, taxes et autres perceptions en matière de contributions indirectes sont réclamés sur un titre de liquidation émis au vu de la déclaration souscrite dans les délais impartis pour les autres droits, taxes et perceptions. Toutefois, l’Administration peut exiger, si besoin est, le paiement préalable des droits et taxes avant enlèvement des produits.\n\nA cet effet, l’agent liquidateur tient un registre de titres de liquidation à souches.\n\nArticle 03.03.03.- Par dérogation aux dispositions qui précèdent, toutes les sommes à percevoir en matière répressive (montant des transactions avant ou après jugement, produits de la vente des objets saisis dont l’abandon au service a été stipulé par transaction ou dont la confiscation a été prononcée par jugement) sont encaissées par le receveur des Impôts sur pièces justificatives tenant lieu de titres de perception : Copie de la transaction ou du jugement, procès-verbal de la vente.\n\nArticle 03.03.04.- Le receveur est personnellement et pécuniairement responsable des opérations dont il est chargé aux termes des articles 03.03.01 à 03.03.03 ci-dessus.\n\nLa gestion des recettes en matière du Droit d’Accises entraîne le bénéfice d’allocation d’indemnité égale à 5% des recettes encaissées et repartie périodiquement suivant les modalités fixées par Décision du Ministre chargé de la règlementation fiscale qui peut déléguer son pouvoir au Directeur Général des Impôts.\n\nArticle 03.03.05.- Une somme prélevée sur les recettes du Droit d’Accises à raison de dix Ariary par paquet de cigarettes est attribuée et versée au profit du Fonds pour la lutte contre la famine dont les modalités d’application sont fixées par voie règlementaire.\n\nArticle 03.03.06.- Au moment de la liquidation du Droit d’Accises, il sera déduit du montant des taxes dues, s’il y a lieu, les déductions règlementaires prévues à l’article II-33 du Code des procédures fiscales.\n\nArticle 03.03.07.- L’agent liquidateur doit procéder à l’enregistrement au «registre des comptes ouverts» des titres de liquidation émis et renseigner ce même registre du numéro et de la date de la quittance ainsi que du montant de la somme recouvrée.\n\nArticles 03.03.08 à 03.03.12.- Abrogés.', 104, NULL, '2025-04-20'),
    (parent_id_var, 'article', 'ART. 10.05.06', E'Article 10.05.06', E'Cf. Article I-113, Code des procédures fiscales.\n\nTout versement effectué par chaque établissement d''hébergement doit faire I’objet de délivrance d''une quittance d''égal montant par l’agent chargé du recouvrement, à titre de pièce justificative pour le redevable.\n\nUne copie de l’état récapitulatif des ordres de recette accompagné d’un état détaillé des versements mensuels reçus doit être adressée, par l’agent chargé du recouvrement avant le quinze du mois qui suit, au bureau de la Région, pour la partie à laquelle elle est bénéficiaire.\n\nCode des Impôts                                                   151', 135, NULL, '2025-04-20'),
    (parent_id_var, 'article', 'ART. 30.01.14', E'Article 30.01.14', E'Les dispositions des articles 10.01.01 et suivants ainsi que des articles 10.02.01 et suivants relatives à l’IFT et à l’IFPB sont applicables au Zones et Entreprises Franches.\n\nArticle 30.01.15.- Sous réserve de l’application des dispositions prévues dans cette partie du Code, les règles d''assiette et de liquidation des impôts, droits et taxes fixées par le Code des impôts demeurent applicables aux Zones et Entreprises Franches.\n\nLes impôts, droits et taxes prévus par le présent Code à la date d’entrée en vigueur de la Loi de Finances portant mise à jour des dispositions régissant les Zones et Entreprises Franches, leur sont applicables.', 135, NULL, '2025-04-20'),
    (parent_id_var, 'article', 'ART. 30.02.01', E'Article 30.02.01', E'Au sens de la présente partie, sauf indication contraire précise, une référence au Code Général des Impôts veut dire le Code Général des Impôts de Madagascar, tel que modifié par la Loi de Finances Rectificative pour 1999 en date du 21 Avril 1999. Toutefois, en application des dispositions de l’article 27 de la loi n° 2001-031 du 08 octobre 2002 établissant un Régime Spécial pour les Grands Investissements dans le Secteur Minier Malagasy modifiée par la Loi n°2005- 022 du 17 octobre 2005 (LGIM), si des mesures fiscales plus favorables au Titulaire, à l’Entité de Transformation, aux Sous-traitants ou aux Investisseurs sont prises par des lois   qui prennent effet entre le 21 Avril 1999 et la Date de Certification de l’Eligibilité de l’Investissement, elles sont applicables aux lieu et place des dispositions correspondantes dudit Code Général des Impôts, sans que le Titulaire, l’Entité de Transformation ou les Investisseurs aient besoin de manifester leur volonté d’opter pour cet ajustement.\n\nEn application des dispositions de l’article 28 de la loi citée précédemment, les dispositions de la présente partie, ne s’appliquent aux Sous-traitants qu’en relation avec les obligations fiscales relatives à leurs opérations pour le compte du Titulaire ou de l’Entité de Transformation dans le cadre des contrats conclus avec l’un ou l’autre d’entre eux.\n\nEn l’absence d’une disposition dérogatoire dans la LGIM, les dispositions du Code Général des Impôts, tel que défini à l’alinéa premier, s’appliquent au Titulaire, à l’Entité de Transformation, aux Sous-traitants et aux Investisseurs.', 135, NULL, '2025-04-20'),
    (parent_id_var, 'article', 'ART. 30.02.23', E'Article 30.02.23', E'Le Titulaire, l''Entité de Transformation et les Sous-traitants sont exonérés de tout centime additionnel prévu par le Code Général des Impôts, ainsi que de tout autre impôt ou taxe qui pourrait être instauré par une province ou par une autre collectivité territoriale décentralisée, excepté les droits de nature parafiscale mentionnés à l’article 61 de la LGIM.\n\nL''Etat Malagasy s''engage à faire respecter les dispositions du présent Code par les provinces autonomes et par les collectivités territoriales décentralisées qui dépendent d''elles conformément à la Constitution. Au cas où une ou plusieurs provinces autonomes ou leurs démembrements augmenteraient ou ajouteraient à la charge fiscale locale du Titulaire, de l''Entité de Transformation ou des Sous-traitants prévue par le présent Code, et l''acte de l''autorité locale serait jugé légal par la juridiction compétente, l''Etat diminuera les charges fiscales au profit du Budget Général de manière à ce que la charge fiscale globale du Titulaire et de l''Entité de Transformation ne dépasse pas celle prévue par le même Code.\n\nLe Gouvernement est autorisé à prendre toutes les mesures nécessaires pour la mise en application de cet engagement.\n\nCode des Impôts                                                   207', 135, NULL, '2025-04-20');

END $$;
