-- Auto-generated SQL inserts for tax code from markdown file (Part 3: Chapters and Sections)
-- Generated on: 2025-04-08

INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE I', 'PRINCIPE', '', 7, 6, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE II', 'CHAMP D’APPLICATION', '', 7, NULL, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE II' LIMIT 1), 'section', 'SECTION I', 'REVENUS IMPOSABLES', '', 7, 6, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE II' LIMIT 1), 'section', 'SECTION II', 'REVENUS EXONERES', '', 7, 6, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE II' LIMIT 1), 'section', 'SECTION III', 'TERRITORIALITE', '', 7, 6, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE II' LIMIT 1), 'section', 'SECTION IV', 'PERSONNES IMPOSABLES', '', 7, NULL, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE III', 'FAIT GENERATEUR', '', 7, 6, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE IV', 'BASE D’IMPOSITION', '', 7, 6, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE V', 'LIEU D’IMPOSITION', '', 7, 6, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE VI', 'REGIME D’IMPOSITION', '', 7, 6, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE VII', 'CALCUL DE L’IMPOT', '', 7, 6, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE VIII', 'PAIEMENT DE L’IMPOT', '', 7, 6, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE IX', 'REDUCTION D’IMPOT A RAISON DES PERSONNES A CHARGE', '', 7, 6, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE X', 'OBLIGATIONS DES CONTRIBUABLES', '', 7, 6, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE XIII' LIMIT 1), 'chapitre', 'CHAPITRE XI', 'DISPOSITIONS DIVERSES', '', 7, NULL, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE XI' LIMIT 1), 'section', 'SECTION V', 'CALCUL DE L’IMPOT', '', 42, 41, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE XI' LIMIT 1), 'section', 'SECTION VI', 'RECOUVREMENT', '', 42, 41, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE XI' LIMIT 1), 'section', 'SECTION VII', 'OBLIGATIONS DU CONTRIBUABLE', '', 42, 68, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE XI' LIMIT 1), 'section', 'SECTION VIII', 'FINANCES – COMPTABILITE PUBLIQUE', '', 69, 68, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE XI' LIMIT 1), 'section', 'SECTION IX', 'ASSISTANCE JUDICIAIRE', '', 69, 68, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'CHAPITRE XI' LIMIT 1), 'section', 'SECTION X', 'DISPOSITIONS DIVERSES', '', 69, NULL, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE V' LIMIT 1), 'chapitre', 'CHAPITRE XII', 'TAXATION D’OFFICE', '', 115, 114, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE V' LIMIT 1), 'chapitre', 'CHAPITRE XIII', 'I- PENALITES SPECIFIQUES', '', 115, 114, '2025-04-08');
INSERT INTO code_sections (parent_id, type, code, title, content, page_number_start, page_number_end, version_date) VALUES ((SELECT id FROM code_sections WHERE code = 'TITRE V' LIMIT 1), 'chapitre', 'CHAPITRE XIV', 'DISPOSITIONS DIVERSES', '', 115, NULL, '2025-04-08');
